version: '3.8'

services:
  postgresdb: 
    image: postgres
    env_file: ./.env
    environment: 
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    ports:
      - $PORT_HOST_DB:$PORT_DOCKER_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    build: .
    depends_on:
      - postgresdb
    links:
      - postgresdb
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT

volumes:
  postgres_data:
    